version: '3'
services:
  offline-web: #前端项目的 service name
    container_name: 'offline-client-container' #容器名称
    build: ./client #根据 client 目录下面的 Dockerfile 构建镜像
    restart: always
    ports:
      - 5001:80
    depends_on:
      - offline-server

  offline-server: #后端项目的service name
    container_name: 'offline-server-container'
    build: ./server #根据 server 目录下面的 Dockerfile 构建镜像
    restart: always
    environment:
      - PORT=5002
      - MYSQL_HOST=122.51.132.117
      - MYSQL_DATABASE=offline
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 5002:5002
